sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t magma-slim .
  - docker tag magma-slim $DOCKER_USERNAME/magma-slim:travis-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/magma-slim:travis-$TRAVIS_BUILD_NUMBER
