sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - docker build -t magma .
  - docker tag magma $DOCKER_USERNAME/lavabit-magma:travis-$TRAVIS_BRANCH
  - docker push $DOCKER_USERNAME/lavabit-magma:travis-$TRAVIS_BRANCH
