sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - docker build -t magma .
  - docker tag magma $DOCKER_USERNAME/lavabit-magma:$TRAVIS_BRANCH-latest
  - docker tag magma $DOCKER_USERNAME/lavabit-magma:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/lavabit-magma:$TRAVIS_BRANCH-latest
  - docker push $DOCKER_USERNAME/lavabit-magma:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
