sudo: required

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t magma-slim .
  - docker tag magma-slim $DOCKER_USER/magma-slim:travis-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/magma-slim:travis-$TRAVIS_BUILD_NUMBER
